### ISSUE TITLE
Suggested improvements

### ISSUE THREAD

**Issue by b286** [openUC2/UC2-Hi2#1]
It's awesome and super cool ❤️ ❤️ ❤️ 

I've went through it critically but there's not much to complain about. Let me know if I should just fix the typos, broken links and these things. 

- [x] Add the short version of the UC2 repository header with link to the main one to keep the style of them alike 
- [x] "Scroll to the very bottom of the page." suggests to skip most of the page. Confusing. Better: "Keep scrolling" or something
- [x] Opentrons OT2, Opentrons Website, CONTRIBUTING, Please find the type of licenses here - broken links
- [x] table of content doesn't appear as a list
- [x] typos: expdreiment, above one need (fullstop missing), Baser Camera, Prusmant, plate is only hold, Screws in the wholes, ~1 mm I would say. (comma missing)
- [x] add link: Nejetools.com
- [x] *The plate can easily adapt all kinds of samples* - add spacing, doesn't format
- [ ] Assembly of the XY Stage - the figure comes before the text related to it - this is confusing as our whole repository is done the other way around
- [x] Credits - no credits there, better say "Collaborate" or so
- [ ] README_SOFTWARE.md - the entry barrier to high but as you said it's still in development :) 
- [ ] README_SOFTWARE.md - figure on the bottom doesn't show

**Comment by beniroquai** [comment]
Thank you very much for making this project so much better :-P 

I updated most of the points listed above! Thanks a lot!!
